# Generated by Django 2.0.13 on 2019-08-16 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190813_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default.png', upload_to='avatars/users_avatars/'),
        ),
    ]
